export const dummyData = [
  {
    courseId: "GEB1112",
    courseName: "크로스오버 1 : 인간의 탐색",
    area: "교양필수",
    status: null,
    credit: "2.0",
    grade: "P",
  },
  {
    courseId: "GEB1107",
    courseName: "의사소통 영어",
    area: "교양필수",
    status: null,
    credit: "3.0",
    grade: "A+",
  },
  {
    courseId: "CON3607",
    courseName: "소비자정량분석 및 실습",
    area: "전공필수",
    status: "주전공",
    credit: "3.0",
    grade: "A+",
  },
  {
    courseId: "CON4602",
    courseName: "현대사회와 소비문화",
    area: "전공선택",
    status: "연계전공",
    credit: "3.0",
    grade: "A+",
  },
  {
    courseId: "CON3404",
    courseName: "고객서비스와 고객관계관리",
    area: "전공선택",
    status: "주전공",
    credit: "3.0",
    grade: "B+",
  },
  {
    courseId: "CCM4322",
    courseName: "광고와 커뮤니케이션",
    area: "전공선택",
    status: "연계전공",
    credit: "3.0",
    grade: "B+",
  },
  {
    courseId: "CCM4322",
    courseName: "행정학개론",
    area: "교양필수",
    status: "연계전공",
    credit: "3.0",
    grade: "A-",
  },
  {
    courseId: "SOS1103",
    courseName: "미디어와 현대사회",
    area: "교양선택",
    status: "연계전공",
    credit: "3.0",
    grade: "A+",
  },
  {
    courseId: "GEB1112",
    courseName: "크로스오버 1 : 인간의 탐색",
    area: "교양필수",
    status: null,
    credit: "2.0",
    grade: "P",
  },
  {
    courseId: "GEB1107",
    courseName: "의사소통 영어",
    area: "교양필수",
    status: null,
    credit: "3.0",
    grade: "A+",
  },
  {
    courseId: "CON3607",
    courseName: "소비자정량분석 및 실습",
    area: "전공필수",
    status: "주전공",
    credit: "3.0",
    grade: "A+",
  },
  {
    courseId: "CON4602",
    courseName: "현대사회와 소비문화",
    area: "전공선택",
    status: "연계전공",
    credit: "3.0",
    grade: "A+",
  },
  {
    courseId: "CON3404",
    courseName: "고객서비스와 고객관계관리",
    area: "전공선택",
    status: "주전공",
    credit: "3.0",
    grade: "B+",
  },
  {
    courseId: "CCM4322",
    courseName: "광고와 커뮤니케이션",
    area: "전공선택",
    status: "연계전공",
    credit: "3.0",
    grade: "B+",
  },
  {
    courseId: "CCM4322",
    courseName: "행정학개론",
    area: "교양필수",
    status: "연계전공",
    credit: "3.0",
    grade: "A-",
  },
  {
    courseId: "SOS1103",
    courseName: "미디어와 현대사회",
    area: "교양선택",
    status: "연계전공",
    credit: "3.0",
    grade: "A+",
  },
];
